# Generated by Django 3.0.6 on 2020-12-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='niche',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
